#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Future Task Mover"
  echo "    future"
  echo "      Moves tasks with @future into future.txt and dated tasks out of"
  echo "      future.txt when the time comes"
  echo ""
  exit
}

[ "$action" = "future" ] && {
     python ${TODO_ACTIONS_DIR}/future.py "$TODO_FILE" "$DONE_FILE"
}
