;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        counsel-M-x
        counsel-yank-pop
        dabbrev-expand
        drag-stuff-up
        electric-newline-and-maybe-indent
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        isearch-repeat-backward
        ivy-occur-dispatch
        kill-region
        mark-sexp
        markdown-outdent-or-delete
        mouse-set-region
        mu4e-headers-mark-for-trash
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-yank
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-word
        sp-remove-active-pair-overlay
        undefined
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-describe-function
        counsel-find-file
        end-of-buffer
        eval-print-last-sexp
        goto-address-at-point
        ivy-switch-buffer
        ivy-wgrep-change-to-wgrep-mode
        mouse-save-then-kill
        save-some-buffers
        swiper
        wgrep-finish-edit
        ))
