;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	counsel-M-x
	counsel-yank-pop
	dabbrev-expand
	drag-stuff-up
	electric-newline-and-maybe-indent
	hungry-delete-backward
	hungry-delete-forward
	kill-region
	mark-sexp
	mouse-set-region
	org-force-self-insert
	org-self-insert-command
	org-yank
	sp-backward-delete-char
	sp-backward-kill-word
	sp-delete-char
	sp-kill-word
	sp-remove-active-pair-overlay
	undefined
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	counsel-describe-function
	counsel-find-file
	end-of-buffer
	goto-address-at-point
	ivy-switch-buffer
	ivy-wgrep-change-to-wgrep-mode
	save-some-buffers
	swiper
	wgrep-finish-edit
	))
